## Python Challenge Day 18

---

#### Q1. Write a program to Create:
#### a 3×3 array of zeros . b 3×3 array of ones . c 3×3 array of random numbers

In [1]:
import numpy as np

zero_array = np.zeros((3,3))

one_array = np.ones((3,3))

random_array = np.random.rand(3,3)

print("3x3 Zeros array:\n",zero_array)
print("Ones Array:\n",one_array)
print("Random array:\n", random_array)

3x3 Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Random array:
 [[0.45732643 0.78220722 0.64750211]
 [0.34038613 0.64663295 0.89340822]
 [0.23689412 0.9909407  0.91413649]]


#### Q2. Write a program to Create an array and sort it als0 find index of a given element

In [2]:
import numpy as np
arr = np.array([45,12,78,34,23])

sorted_array = np.sort(arr)

element = 34
index = np.where(arr == element)

print("Original array:\n",arr)
print("Sorted Array\n",sorted_array)
print(f"Index of {element}:", index[0][0])

Original array:
 [45 12 78 34 23]
Sorted Array
 [12 23 34 45 78]
Index of 34: 3


#### Q3. Write a program to Create two 2×2 matrices and perform matrix multiplication using dot().

In [5]:
import numpy as np

A= np.array([[1,2],[3,4]])
B= np.array([[5,6],[7,8]])

result = np.dot(A,B)

print("Matrix A:", A)
print("Matrix B\n:", B)
print("Matrix Multiplication:",result)

Matrix A: [[1 2]
 [3 4]]
Matrix B
: [[5 6]
 [7 8]]
Matrix Multiplication: [[19 22]
 [43 50]]
